Fcornaire/TF.EX

- src/TF.EX.Patchs/Engine/TFGame.cs
- src/TF.EX.Patchs/Entity/MenuItem/VersusCoinButton.cs
Prevent the game unable to join server if done previously 
Also fixed Match length button (coz why not)
> fix: Disconnect on main

- src/TF.EX.TowerFallExtensions/Level.cs
> fix: attempt to fix spotlight issue

- src/TF.EX.Common/AutoUpdater.cs
- src/TF.EX.Core/meta.json
> fix: update directory trying to be deleted

- src/TF.EX.Domain/Context/GameContext.cs
- src/TF.EX.Domain/Extensions/PlayerArrowsInventory.cs
- src/TF.EX.Domain/Models/State/GameState.cs
- src/TF.EX.Domain/Models/State/Layer/BackgroundElement.cs
- src/TF.EX.Domain/Models/State/Layer/ForegroundElement.cs
- src/TF.EX.Domain/Models/State/Layer/Layer.cs
- src/TF.EX.Domain/Models/State/LevelEntity/Chest/Pickup.cs
- src/TF.EX.Domain/Models/State/Player/Player.cs
- src/TF.EX.Domain/Models/State/Player/PlayerAnimations.cs
- src/TF.EX.Domain/Models/State/Player/PlayerArrowsInventory.cs
- src/TF.EX.Domain/Models/State/Player/PlayerCorpse.cs
- src/TF.EX.Domain/Models/State/Player/PlayerState.cs
- src/TF.EX.Domain/Models/State/Player/PlayerStates.cs
- src/TF.EX.Domain/Models/State/Sprite.cs
- src/TF.EX.Patchs/Entity/LevelEntity/ShieldPickup.cs
- src/TF.EX.Patchs/Layer/Layer.cs
- src/TF.EX.Patchs/ServiceProviderExtensions.cs
- src/TF.EX.TowerFallExtensions/BGElement.cs
- src/TF.EX.TowerFallExtensions/Entity/LevelEntity/Pickup.cs
- src/TF.EX.TowerFallExtensions/Entity/LevelEntity/Player.cs
- src/TF.EX.TowerFallExtensions/Entity/LevelEntity/PlayerCorpseExtensions.cs
- src/TF.EX.TowerFallExtensions/Layer/Background.cs
- src/TF.EX.TowerFallExtensions/Layer/Layer.cs
- src/TF.EX.TowerFallExtensions/Level.cs
- src/TF.EX.TowerFallExtensions/Sprite.cs
Added some animation to be tracked (player, shield, wings, foreground)
Might miss some 
Also fixed a desynchronisation issue with the shield pickup
> feat: track animation + fix shield pickup

- src/TF.EX.Domain/Context/GameContext.cs
- src/TF.EX.Domain/Context/SoundEffectPlaying.cs
- src/TF.EX.Domain/Extensions/SFX.cs
- src/TF.EX.Domain/Models/State/GameState.cs
- src/TF.EX.Domain/Models/State/LevelEntity/JumpPad.cs
- src/TF.EX.Domain/Models/State/Player/Player.cs
- src/TF.EX.Domain/Models/State/SFX.cs
- src/TF.EX.Domain/Ports/TF/ISFXService.cs
- src/TF.EX.Domain/ServiceCollections.cs
- src/TF.EX.Domain/Services/TF/SFXService.cs
- src/TF.EX.Domain/TF.EX.Domain.csproj
- src/TF.EX.Patchs/Monocle.cs
- src/TF.EX.Patchs/SFX/SFX.cs
- src/TF.EX.Patchs/SFX/SFXInstanced.cs
- src/TF.EX.Patchs/Scene/Level.cs
- src/TF.EX.Patchs/Scene/LevelLoaderXML.cs
- src/TF.EX.Patchs/ServiceProviderExtensions.cs
- src/TF.EX.TowerFallExtensions/Entity/LevelEntity/JumpPad.cs
- src/TF.EX.TowerFallExtensions/Entity/LevelEntity/Player.cs
- src/TF.EX.TowerFallExtensions/Level.cs
Not perfect but should be fine for a start
> feat: track SFX (aka preventing multiple SFX playing)

- src/TF.EX.Core/meta.json
> chore : Bump to 0.1.5

- src/TF.EX.Domain/Models/State/Entity/Entity.cs
- src/TF.EX.Domain/Models/State/Entity/LevelEntity/Lava.cs
- src/TF.EX.Domain/Models/State/Entity/LevelEntity/LavaControl.cs
- src/TF.EX.Domain/Models/State/Orb/Orb.cs
- src/TF.EX.Patchs/Entity/LevelEntity/Lava.cs
- src/TF.EX.Patchs/Entity/LevelEntity/LavaControl.cs
- src/TF.EX.Patchs/Entity/TreasureSpawner.cs
- src/TF.EX.Patchs/Layer/Layer.cs
- src/TF.EX.Patchs/OrbLogic.cs
- src/TF.EX.TowerFallExtensions/Entity/LevelEntity/Lava.cs
- src/TF.EX.TowerFallExtensions/Entity/LevelEntity/LavaControl.cs
- src/TF.EX.TowerFallExtensions/Level.cs
Lava was broken before
Should work properly now
> fix re enable lava orb

- src/TF.EX.Common/Extensions/LoggingExtensions.cs
- src/TF.EX.Common/Logging/Logger.cs
- src/TF.EX.Common/TF.EX.Common.csproj
- src/TF.EX.Core/RoundLogic/Netplay1v1DirectRoundLogic.cs
- src/TF.EX.Core/RoundLogic/Netplay1v1QuickPlayRoundLogic.cs
- src/TF.EX.Core/TFCommands.cs
- src/TF.EX.Domain/Ports/INetplayManager.cs
- src/TF.EX.Domain/ServiceCollections.cs
- src/TF.EX.Domain/Services/MatchmakingService.cs
- src/TF.EX.Domain/Services/NetplayManager.cs
- src/TF.EX.Domain/Services/StateMachine/Netplay1V1QuickPlayStateMachine.cs
- src/TF.EX.Domain/Utils/AttributeManager.cs
- src/TF.EX.Patchs/Commands/Commands.cs
- src/TF.EX.Patchs/Engine/TFGame.cs
- src/TF.EX.Patchs/Layer/GameplayLayer.cs
- src/TF.EX.Patchs/PlayerInput/KeyboardInput.cs
- src/TF.EX.Patchs/PlayerInput/XGamePadInput.cs
- src/TF.EX.Patchs/ReplayRecorder.cs
- src/TF.EX.Patchs/Scene/MainMenu.cs
- src/TF.EX.Patchs/Session.cs
- src/TF.EX.TowerFallExtensions/Level.cs
* also using VersusMatchSettings instead of DI in some scenario
* also some small refacto
> feat: custom logger

- src/TF.EX.Common/AutoUpdater.cs
- src/TF.EX.Patchs/Engine/TFGame.cs
Also open a FortRise Console to see advancement
> feat: better auto updater

- src/TF.EX.Patchs/ReplayRecorder.cs
- src/TF.EX.Patchs/Scene/LevelLoaderXML.cs
- src/TF.EX.TowerFallExtensions/Level.cs
Also fixed typo
Also prevent connexion dialog appearing only in netplay mode 
Also prevent ReplayRecorder activating on test mode
> fix: Missing HUDFade on Round Result

- src/TF.EX.Core/RoundLogic/Netplay1v1DirectRoundLogic.cs
- src/TF.EX.Core/RoundLogic/Netplay1v1QuickPlayRoundLogic.cs
- src/TF.EX.Domain/Services/NetplayManager.cs
- src/TF.EX.Domain/Services/ReplayService.cs
- src/TF.EX.Patchs/Engine/TFGame.cs
- src/TF.EX.Patchs/Entity/HUD/HUD.cs
- src/TF.EX.Patchs/Entity/HUD/VersusMatchResults.cs
- src/TF.EX.Patchs/Session.cs
also changed autoupdater behavior to happen at game exit
> fix: replay export even on crash

- src/TF.EX.Core/TFCommands.cs
- src/TF.EX.Core/TFEXModModule.cs
- src/TF.EX.Domain/Context/GameContext.cs
- src/TF.EX.Domain/CustomComponent/Fader.cs
- src/TF.EX.Domain/CustomComponent/ReplayButton.cs
- src/TF.EX.Domain/CustomComponent/ReplayInfos.cs
- src/TF.EX.Domain/CustomComponent/ReplaysPanel.cs
- src/TF.EX.Domain/CustomComponent/Text.cs
- src/TF.EX.Domain/Models/Replay.cs
- src/TF.EX.Domain/Ports/INetplayManager.cs
- src/TF.EX.Domain/Ports/IReplayService.cs
- src/TF.EX.Domain/Ports/TF/IInputService.cs
- src/TF.EX.Domain/ReplayContractResolver.cs
- src/TF.EX.Domain/ServiceCollections.cs
- src/TF.EX.Domain/Services/NetplayManager.cs
- src/TF.EX.Domain/Services/ReplayService.cs
- src/TF.EX.Domain/Services/TF/InputService.cs
- src/TF.EX.Patchs/Engine/TFGame.cs
- src/TF.EX.Patchs/Entity/HUD/HUD.cs
- src/TF.EX.Patchs/Entity/MenuItem/Loader.cs
- src/TF.EX.Patchs/Entity/ScreenTitle.cs
- src/TF.EX.Patchs/InputRenderer.cs
- src/TF.EX.Patchs/Layer/GameplayLayer.cs
- src/TF.EX.Patchs/PlayerInput/KeyboardInput.cs
- src/TF.EX.Patchs/PlayerInput/XGamePadInput.cs
- src/TF.EX.Patchs/Scene/MainMenu.cs
- src/TF.EX.Patchs/Scene/MapScene.cs
- src/TF.EX.Patchs/ServiceProviderExtensions.cs
- src/TF.EX.TowerFallExtensions/Level.cs
- src/TF.EX.TowerFallExtensions/Scene/Scene.cs
> feat: add replay menu

- src/TF.EX.Patchs/Session.cs
This happen because of a previous bad mistake...
> fix: 1F desynchronization

- src/TF.EX.Common/AutoUpdater.cs
Tag name first letter is not capitalized...
> fix: auto updater

- src/TF.EX.Domain/ServiceCollections.cs
accidentally added a lazy<T> to the cache instead of just T ...
> fix: lazy cache

- src/TF.EX.Common/Extensions/EnumerableExtensions.cs
- src/TF.EX.Core/TFEXModModule.cs
- src/TF.EX.Domain/Context/GameContext.cs
- src/TF.EX.Domain/Ports/IArcherService.cs
- src/TF.EX.Domain/Ports/INetplayManager.cs
- src/TF.EX.Domain/ServiceCollections.cs
- src/TF.EX.Domain/Services/ArcherService.cs
- src/TF.EX.Domain/Services/MatchmakingService.cs
- src/TF.EX.Domain/Services/NetplayManager.cs
- src/TF.EX.Domain/Services/ReplayService.cs
- src/TF.EX.Domain/Services/StateMachine/Netplay1V1DirectStateMachine.cs
- src/TF.EX.Domain/Services/StateMachine/Netplay1V1QuickPlayStateMachine.cs
- src/TF.EX.Domain/Services/StateMachine/NetplayStateMachine.cs
- src/TF.EX.Patchs/Engine/TFGame.cs
- src/TF.EX.Patchs/Entity/MenuItem/RollCallElement.cs
- src/TF.EX.TowerFallExtensions/Level.cs
> fix: archer swap + swapped info in replay

- src/TF.EX.Common/Handle/SafeBytes.cs
- src/TF.EX.Domain/ServiceCollections.cs
- src/TF.EX.Domain/Services/MatchmakingService.cs
- src/TF.EX.Domain/Services/NetplayManager.cs
- src/TF.EX.Patchs/Engine/TFGame.cs
- src/TF.EX.Patchs/Entity/MenuItem/RollCallElement.cs
- src/TF.EX.Patchs/Entity/MenuItem/VersusBeginButton.cs
> fix: clearing archer selection too early

- src/TF.EX.Domain/DebugLayer.cs
- src/TF.EX.Domain/Models/State/Component/Alarm.cs
- src/TF.EX.Domain/Models/State/Component/Counter.cs
- src/TF.EX.Domain/Models/State/Component/FireControl.cs
- src/TF.EX.Domain/Models/State/Entity/Entity.cs
- src/TF.EX.Domain/Models/State/Entity/LevelEntity/Arrows/Arrow.cs
- src/TF.EX.Domain/Models/State/Entity/LevelEntity/BGTorch.cs
- src/TF.EX.Domain/Models/State/Entity/LevelEntity/CrackedPlatform.cs
- src/TF.EX.Domain/Models/State/Entity/LevelEntity/Explosion.cs
- src/TF.EX.Domain/Models/State/Entity/LevelEntity/Player/Player.cs
- src/TF.EX.Domain/Models/State/Entity/LevelEntity/Spikeball.cs
- src/TF.EX.Domain/Models/State/OrbLogic/Space.cs
- src/TF.EX.TowerFallExtensions/Component/Alarm.cs
- src/TF.EX.TowerFallExtensions/Component/Counter.cs
- src/TF.EX.TowerFallExtensions/Component/FireControl.cs
- src/TF.EX.TowerFallExtensions/Entity/LevelEntity/Arrow.cs
- src/TF.EX.TowerFallExtensions/Entity/LevelEntity/BGTorch.cs
- src/TF.EX.TowerFallExtensions/Entity/LevelEntity/CrackedPlatform.cs
- src/TF.EX.TowerFallExtensions/Entity/LevelEntity/Explosion.cs
- src/TF.EX.TowerFallExtensions/Entity/LevelEntity/Player.cs
- src/TF.EX.TowerFallExtensions/Entity/LevelEntity/SpikeBall.cs
- src/TF.EX.TowerFallExtensions/Level.cs
- src/TF.EX.TowerFallExtensions/OrbLogic.cs
Mostly for player wings but can probably be useful in other case
> feat: track fire(torch , player and arrow)

- EX-API.md
- src/TF.EX.Common/AutoUpdater.cs
- src/TF.EX.Domain/CustomComponent/Notification.cs
- src/TF.EX.Domain/Extensions/MatchVariants.cs
- src/TF.EX.Patchs/Engine/TFGame.cs
- src/TF.EX.Patchs/Scene/MainMenu.cs
used in lobby and auto updater
> feat: Notification

- EX-API.md
- README.md
- src/TF.EX.Domain/Services/NetplayManager.cs
+ made spectate error redirect to versus options
> chore: added some docs

- src/TF.EX.Common/Extensions/LoggingExtensions.cs
- src/TF.EX.Domain/CustomComponent/Notification.cs
- src/TF.EX.Domain/Models/WebSocket/Client/ArcherSelectChoiceMessage.cs
- src/TF.EX.Domain/Models/WebSocket/Client/RematchLobbyChoiceMessage.cs
- src/TF.EX.Domain/Models/WebSocket/Lobby.cs
- src/TF.EX.Domain/Models/WebSocket/Server/ArcherSelectMessage.cs
- src/TF.EX.Domain/Models/WebSocket/Server/LeaveLobbyForceMessage.cs
- src/TF.EX.Domain/Models/WebSocket/Server/RematchLobbyMessage.cs
- src/TF.EX.Domain/Ports/IMatchmakingService.cs
- src/TF.EX.Domain/Services/MatchmakingService.cs
- src/TF.EX.Domain/Services/NetplayManager.cs
- src/TF.EX.Patchs/Engine/TFGame.cs
- src/TF.EX.Patchs/Entity/HUD/VersusPlayerMatchResults.cs
- src/TF.EX.Patchs/Entity/PauseMenu.cs
Rematch/Archer/Quit
Also reset rng every rematch
> feat: Synchronize end game option

- src/TF.EX.Domain/CustomComponent/ReplaysPanel.cs
- src/TF.EX.Domain/Extensions/ArcherData.cs
- src/TF.EX.Domain/Services/MatchmakingService.cs
- src/TF.EX.Domain/Services/ReplayService.cs
- src/TF.EX.Patchs/Scene/MainMenu.cs
This make ArcherLoader mod work
> feat: Added support for custom archer

- src/TF.EX.Common/AutoUpdater.cs
- src/TF.EX.Patchs/Scene/LevelLoaderXML.cs
- src/TF.EX.Patchs/Scene/MainMenu.cs
Fixed some text consistency issues and grammar issues, no functional changes
> Minor text changes

- src/TF.EX.Domain/Ports/TF/IInputService.cs
- src/TF.EX.Domain/Services/TF/InputService.cs
- src/TF.EX.Patchs/Entity/MenuItem/VersusBeginButton.cs
- src/TF.EX.Patchs/Entity/TreasureSpawner.cs
- src/TF.EX.Patchs/Scene/MainMenu.cs
also fix lobby leaving in main menu
> fix: Add fake controllers (replay)

- src/TF.EX.Core/meta.json
- src/TF.EX.Patchs/PlayerInput/KeyboardInput.cs
- src/TF.EX.Patchs/PlayerInput/XGamePadInput.cs
- src/TF.EX.Patchs/Scene/MainMenu.cs
> fix: Refactor player input handling and update

- src/TF.EX.Domain/Models/State/Constants.cs
- src/TF.EX.Utils/ReplayComparer.cs
All flight elements was already tracked by previous map
> feat: Track Fligth

- README.md
Also updates the instructions for opening the console
Also removes the part about blank screen when requesting rematch, should be irrelevant now
> Update README.md to reference new lobby system

- src/TF.EX.Domain/FakeController.cs
- src/TF.EX.Domain/Ports/IReplayService.cs
- src/TF.EX.Domain/Services/ReplayService.cs
- src/TF.EX.Patchs/InputRenderer.cs
- src/TF.EX.Patchs/Layer/GameplayLayer.cs
- src/TF.EX.Utils/ReplayComparer.cs
This should:
- properly show the input renderer according to the archer related
- make the replay controller actually retrieve replay input
> fix: Some replay playback fix

- src/TF.EX.Domain/Services/MatchmakingService.cs
- src/TF.EX.Domain/Services/NetplayManager.cs
Changes "Connexion dropped..." to "Connection dropped"
> Fix disconnect text
